---
title: "Size and Shaft on RORB data"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    fig_height: 10
    fig_width: 10
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 2
---
```{r knitOPTS, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, dev = "png")
knitr::opts_chunk$set(engine.path = 
  list( 
      python = '/Library/Frameworks/Python.framework/Versions/3.6/bin/python3'
      )
)
```

```{r render, eval=FALSE, echo=FALSE}
require(rmarkdown)
require(knitr)
rmarkdown::render("rorb_shaft.Rmd"); system("open rorb_shaft.html -a /Applications/Chrome.app")
```

```{r setup,include=FALSE,results='asis',message=FALSE,warning=FALSE, echo = FALSE}
# Library calls here.
require(rmarkdown)
require(NMF)
require(knitr)
require(MASS)
require(doMC)
require(foreach)
require(scales)
require(raster)
require(mgc)
registerDoMC(6)
suppressMessages(require(meda))
```

# Python code to download annotation sizes from the BOSS 

```{python, eval = FALSE}
from intern.remote.boss import BossRemote
from intern.resource.boss.resource import *
from intern.utils.parallel import block_compute
import configparser
import requests
import numpy as np
from numpy import genfromtxt
import shutil
import blosc
import sys
import os
import itertools
from functools import partial
from multiprocessing import Pool
from multiprocessing.dummy import Pool as ThreadPool
from multiprocessing import cpu_count
import csv
import argparse


####
CONFIG_FILE    = 'neurodata.conf'

COLL_NAME      = 'collman' 
EXP_NAME       = 'M247514_Rorb_1_Site3Align2_EM' 
ANNO_NAME      = 'm247514_Site3Annotation_MN_global'
COORD_FRAME    = 'M247514_Rorb_1_Site3Align2_EM_m247514_Site3Annotation_MN_global'
OUTPUT         = 'annotation_sizes_pixels.csv'

config = configparser.ConfigParser()
config.read(CONFIG_FILE)
TOKEN = config['Default']['token']
boss_url = ''.join( ( config['Default']['protocol'],'://',config['Default']['host'],'/v1/' ) )
#print(boss_url)
#'https://api.boss.neurodata.io/v1/'

#intern
rem = BossRemote(CONFIG_FILE)

cf = CoordinateFrameResource(str(COLL_NAME + '_' + EXP_NAME))
cfr = rem.get_project(cf)
anno_res = ChannelResource(ANNO_NAME, COLL_NAME, EXP_NAME, 'annotation', datatype='uint64')

ex = {'x': cfr.x_stop, 'y': cfr.y_stop, 'z': cfr.z_stop}

blocks = block_compute(0,ex['x'],0,ex['y'],0,ex['z'],
           origin = (0,0,0), block_size = (512, 512, 16))

rid = []
for b in blocks:
    rid = rid + rem.get_ids_in_region(anno_res, 0, b[0], b[1], b[2], [0,1])


u = np.unique(np.asarray(rid))

def getSizeAnno(uniq):
    bb = rem.get_bounding_box(anno_res, 0, uniq, 'tight')
    out = [bb['id'], sizeAnno]
    return(out)

with ThreadTool(4) as tp:
    bbA  = np.asarray(tp.map(getSizeAnno, u))

with open(OUTPUT, 'w') as f1:
        wt = csv.writer(f1)
        wt.writerow(['id', 'size'])
        wt.writerows(bbA)

```

```{r start, eval = TRUE}
na <- read.csv("rorb_gaussianAvg_at.csv")
cnames <- colnames(na)
dat <- fread("rorb_gaussianAvg_at.csv")
colnames(dat) <- cnames
loc <- read.csv("rorb_avg_at_orderLocations.csv")

ids <- read.csv("rorb_avg_at_orderIDS.csv")
colnames(ids) <- 'ids'
gabaID <- read.csv("rorb_gaba.csv")
truth <- gaba <- gabaID$gaba
truth <- as.factor(truth)

ccol <- c('blue', 'blue', 'blue', 'red', 'red', 'red', 'black', 'black', 'green', 'green', 'black', 'green')
ind <- order(ccol)
ccol <- sort(ccol)

gabaID <- read.csv("rorb_gaba.csv")
shaftID <- read.csv("rorb_shaft.csv")
TdID <- read.csv("rorb_TdTom.csv")

TdTom <- TdID$TdTom
TdTom[TdTom %in% 3] <- 2 ## ASK ABOUT THIS
shaft <- shaftID$shaft
gaba <- truth <- gabaID$gaba

ccol <- c('blue', 'blue', 'blue', 'red', 'red', 'red', 'green', 'black', 'green', 'green', 'black', 'green')
ind <- order(ccol)
ccol <- sort(ccol)

## annotation ids in the BOSS are +1 from the ids in Forrest's gsheet.
annoSizes <- read.csv('annotation_sizes_pixels.csv')
annoSizes$id <- annoSizes$id - 1

ids$size <- -1
for(i in ids[[1]]){
  ids[ids[[1]] == i,]$size <- 
  annoSizes[annoSizes$id == i,]$size
}

sdat <- data.table(scale(dat, center = TRUE, scale = TRUE))
```




```{r size, fig.height = 10, fig.width = 10}
sdat$shaft <- shaft
sdat$gaba <- gaba
sdat$size <- ids$size
sdat$microm3 <- sdat$size * 3*3*50 / 1000^3

df1 <- sdat[, .(shaft =as.factor(shaft), size, microm3, PSD95)]

p <- ggplot(df1, aes(x = microm3, y = PSD95, color = shaft, shape = as.factor(gaba))) +
     geom_point(alpha = 0.4) + 
     scale_color_manual(values = c("red", "black")) +
     xlab(expression(paste(mu, "m^3"))) +
     ggtitle("PSD95 versus size colored by shaft")

p + geom_smooth(method = "lm")
```




# KDE's 

```{r hist, fig.height = 4, fig.width = 8}
p2 <- ggplot(sdat, aes(group = shaft))

p2 + geom_density(aes(x = PSD95, y = ..density.., col = as.factor(shaft))) + ggtitle("PSD95 | shaft") + facet_grid(. ~ gaba, labeller = label_both)

p2 + geom_density(aes(x = PSD95, y = ..density.., col = as.factor(shaft))) + ggtitle("PSD95 | shaft") + facet_grid(. ~ gaba, labeller = label_both)

p2 + geom_density(aes(x = microm3, y = ..density.., col = as.factor(shaft))) + ggtitle("size | shaft") + facet_grid(. ~ gaba, labeller = label_both)

p2 + geom_density(aes(x = microm3, y = ..density.., col = as.factor(shaft))) + scale_x_log10() + ggtitle("size | shaft, x-axis on log10 scale") + facet_grid(. ~ gaba, labeller = label_both)


p2 + geom_violin(aes(x = as.factor(shaft), y = PSD95)) + geom_jitter(aes(x = as.factor(shaft), y = PSD95), alpha = 0.7) + facet_grid(. ~ gaba, labeller = label_both)
p2 + geom_violin(aes(x = as.factor(shaft), y = microm3)) + geom_jitter(aes(x = as.factor(shaft), y = microm3), alpha = 0.7) + facet_grid(. ~ gaba, labeller = label_both)

p2 + geom_boxplot(aes(x = as.factor(shaft), y = PSD95), notch = TRUE) + facet_grid(. ~ gaba, labeller = label_both)
p2 + geom_boxplot(aes(x = as.factor(shaft), y = microm3), notch = TRUE) + facet_grid(. ~ gaba, labeller = label_both)
```







