---
title: "RORB Data: 2-class exploration"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 2
---
```{r knitOPTS, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, dev = "png")
```

```{r render, eval=FALSE, echo=FALSE}
require(rmarkdown)
require(knitr)
```

```{r setup,include=FALSE,results='asis',message=FALSE,warning=FALSE, echo = FALSE}
# Library calls here.
require(rmarkdown)
require(knitr)
require(doMC)
require(foreach)
require(scales)
require(kernlab)
require(dimRed)
registerDoMC(4)
suppressMessages(require(meda))
```

```{r, eval = TRUE, echo = FALSE, include = FALSE}
dat <- read.csv("rorb_gaussianAvg_at.csv")
loc <- read.csv("rorb_gaussianAvg_at_orderLocations.csv")
gabaID <- read.csv("rorb_gaba.csv")
truth <- gaba <- gabaID$gaba

ccol <- c('blue', 'blue', 'blue', 'red', 'red', 'red', 'black', 'black', 'green', 'green', 'black', 'green')
ind <- order(ccol)
ccol <- sort(ccol)

dat <- dat[,ind]
sdat <- as.matrix(scale(dat, center = TRUE, scale = TRUE))
```


# 2-class exploration


```{r c2}
c0 <- sdat[!gaba,]
c1 <- sdat[!!gaba,]
```



```{r runAll, eval = TRUE, echo = FALSE, include = FALSE}
set.seed(3174)
Lt0 <- runAll(c0, ccol = ccol)
Lt1 <- runAll(c1, ccol = ccol)
Lt0[[1]] <- mlocation(dat[!gaba,], ccol = ccol)
Lt1[[1]] <- mlocation(dat[!!gaba,], ccol = ccol)

w = 720
h = 720 

png("d1heat_c2.png", width = w, height = h)
p1 <- plot(Lt0[[2]]) 
p1
p2 <- plot(Lt1[[2]]) 
p2
dev.off()

png("mlocation_c2.png", width = 720, height = 480)
p1 <- plot(Lt0[[1]]) 
p1
p2 <- plot(Lt1[[1]])
p2
dev.off()

png("cumulativeVariance_c2.png", width = w, height = h)
p1 <- plot(Lt0[[3]]) 
p1
p2 <- plot(Lt1[[3]])
p2
dev.off()

png("outliers_c2.png", width = w, height = h)
p1 <- plot(Lt0[[4]]) 
p1
p2 <- plot(Lt1[[4]])
p2
dev.off()

png("cor_c2.png", width = w, height = h)
plot(Lt0[[6]]) 
plot(Lt1[[6]])
dev.off()

png("pairhex_c2.png", width = w, height = h)
pairhex(c0)
pairhex(c1)
dev.off()

png("hmcClassifications_c2.png", width = w, height = h)
cr0 <- viridis(max(Lt0[[7]]$dat$labels$col))
cr1 <- viridis(max(Lt1[[7]]$dat$labels$col))
pairs(Lt0[[7]]$dat$data, pch = 19, cex = 0.5, col = cr0[Lt[[7]]$dat$labels$col])
pairs(Lt1[[7]]$dat$data, pch = 19, cex = 0.5, col = cr1[Lt[[7]]$dat$labels$col])
dev.off()

png("dendrograms_c2.png", width = w, height = h)
plotDend(Lt0[[7]])
plotDend(Lt1[[7]])
dev.off()

png("stackMeans_c2.png", width = w, height = 2*h)
p1 <- stackM(Lt0[[7]], ccol = ccol, depth = 3, centered = TRUE)
p1
dev.off()

png("clusterMeans_c2.png", width = w, height = 0.75*h)
p1 <- clusterMeans(Lt[[7]], ccol = ccol)
p1
dev.off()
```



```{r gg-kde}
df1 <- melt(data.frame(sdat, gaba = gaba))




ggplot(mc0, aes(x=value)) + 
    facet_wrap( ~ Var2, scale='free', ncol=6) +
    geom_histogram(aes(y=..density.., group = Var2, color = ccol[as.numeric(mc0$Var2)]), bins = 50) +
    scale_color_manual(values="blue") +
    scale_fill_manual(values="blue") 
    #geom_histogram(aes(y=..density..,group=channel,colour=channel),bins=100) +
    #geom_density(aes(group=channel, color=channel),size=1.5) +
    #theme(plot.title=element_text(size=ts),
    #      axis.title.x=element_text(size=ts),
    #      axis.title.y=element_text(size=ts),
    #      legend.title=element_text(size=ts),
    #      legend.text=element_text(size=ts-2),
    #      axis.text=element_text(size=ts-2),
    #      strip.text=element_text(size=ts), 
    #      legend.position='none')+
    #ggtitle("Kernel Density Estimates of `log1f` data.")

print(gg1)

```



