---
title: "Rorb data"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 2
---
```{r knitOPTS, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, dev = "png")
```

```{r render, eval=FALSE, echo=FALSE}
require(rmarkdown)
require(knitr)
rmarkdown::render("rorb_meda_plots_vectorize.Rmd")
system("open rorb_meda_plots_vectorize.html -a /Applications/Chrome.app")
```

```{r setup,include=FALSE,results='asis',message=FALSE,warning=FALSE, echo = FALSE}
# Library calls here.
require(rmarkdown)
require(knitr)
require(doMC)
require(foreach)
require(scales)
require(kernlab)
require(raster)
require(dimRed)
registerDoMC(4)
suppressMessages(require(meda))
```

```{r, echo = FALSE, include = FALSE}
#dat <- fread("rorb_vectorize_at.csv", header = FALSE)
#loc <- read.csv("rorb_gaussianAvg_at_orderLocations.csv")
#gabaID <- read.csv("rorb_gaba.csv")
#truth <- gaba <- gabaID$gaba
#
#ccol <- c('blue', 'blue', 'blue', 'red', 'red', 'red', 'black', 'black', 'green', 'green', 'black', 'green')
#ind <- order(ccol)
#ccol <- sort(ccol)
#
#sdat <- data.table(scale(dat, center = TRUE, scale = TRUE))
#ccol <- rep("black", 5)
#
na <- read.csv("rorb_gaussianAvg_at.csv")
cnames <- colnames(na)
dat <- fread("rorb_vectorize_at.csv")
loc <- read.csv("rorb_avg_at_orderLocations.csv")
ids <- read.csv("rorb_avg_at_orderIDS.csv")
gabaID <- read.csv("rorb_gaba.csv")
truth <- gaba <- gabaID$gaba
truth <- as.factor(truth)

ccol <- c('blue', 'blue', 'blue', 'red', 'red', 'red', 'black', 'black', 'green', 'green', 'black', 'green')
ind <- order(ccol)
ccol <- sort(ccol)


ind <- lapply(1:1331, function(x) seq(x, 11^3 * 12, by = 1331))

tmp <- Reduce(rbind, lapply(ind, function(ind) {
                              tmp <- dat[, ind, with = FALSE]
                              colnames(tmp) <- sprintf('c%02d', 1:12)
                              return(tmp)
                              }
                              ))

pix <- cbind(gaba = gaba, tmp)
colnames(pix)[-1] <- cnames
spix <- scale(pix[-1], center = TRUE, scale = TRUE)
```


# SVD

```{r pca}
pc <- prcomp(spix, retx = TRUE)
getElbows(pc$sdev)

#plot(raster(pc$rot[, 1:10]), col = colorRampPalette(c('black', 'white', 'red'))(255))

df1 <- data.table(gaba, pc$x)
pairs(pc$x[, 1:3], col = scales::alpha(gaba + 1, 0.5), pch = 20)


ld1 <- lda(as.factor(gaba) ~ pc$x[, 1:3])
table(predict(ld1)$class, gaba)
sum(predict(ld1)$class != gaba)/length(gaba)

qd1 <- qda(as.factor(gaba) ~ pc$x[, 1:3])
table(predict(qd1)$class, gaba)
sum(predict(qd1)$class != gaba)/length(gaba)
```

## LDA and QDA

Next, applying LDA and QDA iterating on the number of PCA dimension
included. 
```{r lda-gaba}
ldaL <- foreach(x = 1:791) %dopar% {
           ldatmp <- lda(gaba ~ pc$x[, 1:x], CV = FALSE)
           predict(ldatmp)
}

qdaL <- foreach(x = 1:84) %dopar% {
           qdatmp <- qda(as.factor(gaba) ~ pc$x[, 1:x], CV = FALSE)
           predict(qdatmp)
}

rfL <- foreach(x = 1:ncol(pc$x)) %dopar% {
           tmpdat <- as.matrix(pc$x[, 1:x])
           set.seed(x)
           rftmp <- randomForest(x = tmpdat, y = as.factor(gaba))
           predict(rftmp)
}

ll <- sapply(lapply(ldaL, '[[', 1), function(x) sum(x != gaba)/length(gaba))
ql <- sapply(lapply(qdaL, '[[', 1), function(x) sum(x != gaba)/length(gaba))
rl <- sapply(rfL, function(x) sum(x != gaba)/length(gaba))


#png(file = "~/Desktop/lda_qda_pcaOnPixels.png", 1080,720)
plot(x = 1:ncol(pc$x), y = seq(0,max(ll,ql),length = ncol(pc$x)), type = 'n', xlab = expression(hat(d)), ylab = "L")
points(ll, type = 'b', col = 'blue', pch = 20, cex = 0.8)
points(ql, type = 'b', col = 'orange', pch = 15, cex = 0.8)
points(rl, type = 'b', col = 'darkgreen', lty = 2, pch = 3)
abline(h = sum(gaba == 1)/length(gaba), col = 'magenta', lty=4)
text(10,max(ql), label = "qda", col = 'orange', pos = 4)
text(10, min(ll), label = "lda", col = 'blue', pos = 1)
text(400,sum(gaba == 1)/length(gaba), label = "chance", col = 'magenta', pos = 1)
#dev.off()

qmm <- sapply(1:12, function(x) sum((gaba - qdaL[[x]]$post[, 1])^2))
lmm <- sapply(1:12, function(x) sum((gaba - ldaL[[x]]$post[, 1])^2))
```



