---
title: "NMF on RORB data"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 2
---
```{r knitOPTS, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, dev = "png")
knitr::opts_chunk$set(engine.path = 
  list( 
      python = '/Library/Frameworks/Python.framework/Versions/3.6/bin/python3'
      )
)
```

```{r render, eval=FALSE, echo=FALSE}
require(rmarkdown)
require(knitr)
rmarkdown::render("rorb_meda_plots_NMF.Rmd"); system("open rorb_meda_plots_NMF.html -a /Applications/Chrome.app")
```

```{r setup,include=FALSE,results='asis',message=FALSE,warning=FALSE, echo = FALSE}
# Library calls here.
require(rmarkdown)
require(NMF)
require(knitr)
require(MASS)
require(doMC)
require(foreach)
require(scales)
require(raster)
registerDoMC(4)
suppressMessages(require(meda))

require("gsl")
require(viridis)
require(magick)
```

# Python code to download a test area from the BOSS

```{python, eval = FALSE}
#
import argparse
import math
from intern.remote.boss import BossRemote
from intern.resource.boss.resource import *
import configparser
#import grequests # for async requests, conflicts with requests somehow
import requests
import numpy as np
from numpy import genfromtxt
import h5py
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import shutil
import blosc
from IPython.core.debugger import set_trace
import sys
import os
import itertools
from functools import partial
from multiprocessing import Pool
from multiprocessing.dummy import Pool as ThreadPool
from multiprocessing import cpu_count
import csv
import datetime

def getCube(di):
    data = di['rem'].get_cutout(di['ch_rsc'], di['res'], di['xrng'],
          di['yrng'] ,di['zrng'])
    print(di['loc']) #DEBUG
    sys.stdout.flush() #DEBUG
    ### OUTPUT will be a numpy array in Z Y X order 
    #avg = np.mean(data)
    return(data)

CONFIG_FILE = "neurodata.conf"
COLL_NAME = "collman"
EXP_NAME = "M247514_Rorb_1_Site3Align2_LENS_Session1_CROP"
COORD_FRAME = COLL_NAME + "_" + EXP_NAME

CHAN_NAMES = ['DAPI1', 'DAPI2', 'DAPI3', 'GABA', 'GAD2', 'Gephyrin', 'GluN1',
                'MBP', 'PSD95', 'synapsin', 'TdTomato', 'VGlut1']


config = configparser.ConfigParser()
config.read(CONFIG_FILE)
TOKEN = config['Default']['token']
boss_url = ''.join( ( config['Default']['protocol'],'://',config['Default']['host'],'/v1/' ) )
#print(boss_url)
#'https://api.boss.neurodata.io/v1/'

#intern
rem = BossRemote(CONFIG_FILE)

chres = [ChannelResource(ch,COLL_NAME,EXP_NAME,'image',datatype='uint8') for ch in CHAN_NAMES]

data = []
for i in range(len(chres)):
  data.append(rem.get_cutout(chres[i],0, [100,300],[100,300],[12,25]))

colMaj = [data[i].flatten() for i in range(len(data))]

out = np.asarray(colMaj)

head = "DAPI1, DAPI2, DAPI3, GABA, GAD2, Gephyrin, GluN1, MBP, PSD95, synapsin, TdTomato, VGlut1"

np.savetxt("test1Cube.csv", np.transpose(out), delimiter = ',', fmt = "%d", header = head)
```

```{r start, eval = TRUE, echo = FALSE, include = FALSE}
na <- read.csv("rorb_gaussianAvg_at.csv")
cnames <- colnames(na)
gavg <- fread("rorb_gaussianAvg_at.csv")
dat <- fread("rorb_vectorize_at.csv")
loc <- read.csv("rorb_avg_at_orderLocations.csv")
ids <- read.csv("rorb_avg_at_orderIDS.csv")
gabaID <- read.csv("rorb_gaba.csv")
truth <- gaba <- gabaID$gaba
truth <- as.factor(truth)

ccol <- c('blue', 'blue', 'blue', 'red', 'red', 'red', 'black', 'black', 'green', 'green', 'black', 'green')
ind <- order(ccol)
ccol <- sort(ccol)


ind <- lapply(1:1331, function(x) seq(x, 11^3 * 12, by = 1331))

tmp <- Reduce(rbind, lapply(ind, function(ind) {
                              tmp <- dat[, ind, with = FALSE]
                              colnames(tmp) <- sprintf('c%02d', 1:12)
                              return(tmp)
                              }
                              ))

pix <- cbind(gaba = gaba, tmp)
colnames(pix)[-1] <- cnames
```


```{r pix}
zi <- apply(pix[,-1], 1, function(x) all(x ==0))
nmpix <- nmf(pix[!zi,-1], 3)
tH <- t(nmpix@fit@H)
```

## A test case

Using a chunk from the RORB data at `x = [100,300], y = [100,300], z = [12,25]`


```{r test}
cu <- fread("test1Cube.csv")
colnames(cu) <- cnames
ind <- apply(cu, 1, function(x) all(x ==0))

col8 <- as.numeric(cu[,8][[1]])
b1 <- array(col8, dim = c(200,200,13))
plot(raster::brick(b1, transpose = TRUE), col = gray.colors(255))

nam <- cu[!ind,]
tmp <- matrix(NA, nrow(cu), 3)
tmp[ind,] <- 0


N <- foreach(x = c(1:ncol(nam))) %dopar% {
    nmf(nam, rank = x)
}

err <- 
foreach(x = 1:ncol(nam), .combine = 'c') %do% {
  norm(as.matrix(nam) - (N[[x]]@fit@W %*% N[[x]]@fit@H), "F")^2 / 
      norm(as.matrix(nam), "F")^2
}

getElbows(err)


#for(i in 2:5){
#  if(i < 3){
#    tmp[!ind, 1:i] <- N[[i]]@fit@W
#  } else {
#    tmp[!ind,1:3] <- N[[i]]@fit@W[,1:3]
#  }
#  am <- array(tmp, dim = c(200,200,i))
#  show(plotRGB(raster::brick(am), r = 1, g = 2, b = 3))
#  show(plot(raster::brick(am, transpose = TRUE)))
#  show(heatmap(N[[i]]@fit@H, col = gray.colors(255)))
#}

tmp[!ind,] <- N[[3]]@fit@W[, 1:3]
am <- array(tmp, dim = c(200,200,3))
plotRGB(raster::brick(am))
```


```{r pca-test, eval = FALSE, include = FALSE}
pc <- prcomp(cu, center = TRUE, scale = TRUE)
b1 <- array(pc$x[, 1:3], dim = c(200,200,3))

plot(raster::brick(b1))
am <- array(as.numeric(as.matrix(cu)), dim = c(200,200,13))
```


```{r anno}
a <- raster("uint16TEST.tiff", xmn = 0, xmx = 200, ymn=0, ymx=200)
b <- raster::brick(b1, xmn = 0, xmx = 200, ymn=0, ymx=200)
plot(b)

plot(raster::brick(b1,a))
```



# Gaussian blurred 


```{r gb}
v <- lapply(cu, function(x) array(x/255, dim = c(200,200,13)))
vv <- abind(v, along = 0)

dimnames(vv)[1]
dim(vv)

plot(raster::brick(vv[12,,,1:13]))

img <- lapply(v, function(x) image_read((x/255)))

lapply(v, function(x) lapply(1:13, function(y) image_read(x[[y]])))
si <- sample(length(img), 10)

kern <- matrix(0, ncol = 3, nrow = 3)
kern[1, 2] <- 0.25
kern[2, c(1, 3)] <- 0.25
kern[3, 2] <- 0.25
kern

imconv <- lapply(img, function(x) image_convolve(x, kernel = "Gaussian", iterations = 10))

for(i in si){
  show(plot(img[[i]]))
  Sys.sleep(0.5)
  show(plot(imconv[[i]]))
}


```

