---
title: "Generate ndviz links for synapse detections"
author: "Jesse Leigh Patsolic"
output: 
  html_document:
    keep_md: true
---

```{r render, eval=FALSE, echo=FALSE}
require(rmarkdown)
rmarkdown::render("genLinks.Rmd")
system('open genLinks.html')
```


```{r cc1}
suppressPackageStartupMessages(require(rhdf5))
suppressPackageStartupMessages(require(meda))

#h5ls("../../data/Anish_csvfiles/XYZ/AnishLocationsFull.h5")
dat <- data.table(h5read("../../data/Anish_csvfiles/XYZ/AnishLocationsFull.h5", name = "Locations/locs"))
exlev <- h5read("../../data/Anish_csvfiles/XYZ/AnishLocationsFull.h5", name = "Levels/Ex")
qlev <-  h5read("../../data/Anish_csvfiles/XYZ/AnishLocationsFull.h5", name = "Levels/Q")

dat$Ex <- as.factor(dat$Ex); levels(dat$Ex) <- exlev 
dat$Q <- as.factor(dat$Q); levels(dat$Q) <- qlev 

H5close()

subd <- dat[Ex == "Ex2R18C1" & 
            row < 100 & 
            row > 50 &
            z < 13.5 & 
            z > 12.5 & 
            col < 700]

xyz <- subd[, `:=`(col = round(col),
            row = round(row), 
            z = round(z))][, .(col, row, z)]

l <- mapply(function(x,y,z){
  sprintf("http://viz.neurodata.io/project/exqc/xy/0/%d/%d/%d/",x,y,z)
  }, xyz$col, xyz$row, xyz$z)

#lapply(l, function(x){ system(paste("open ", x))})
print(l)
```




